#!/bin/sh

# 1st param is the app name in tomcat
# 2nd param is the app name in src/main/webapp
# Script copies dir in src into tomcat

if [  -z "$CATALINA_HOME" ]
then
	echo 'You must set $CATALINA_HOME'
	exit 1
fi

if [ $# -ne 2 ]       
then
    echo 'Usage: Specify app name and dir name'
    exit 1
fi

APP=$1
DIR=$2
TOMCAT=$CATALINA_HOME/webapps/$APP/$DIR
SRC="src/main/webapp/$DIR"

if [ -d $TOMCAT ]
then
	echo "$TOMCAT exists in tomcat, deleting..."
	rm -rf $TOMCAT
else
	echo "$TOMCAT does not exist in tomcat - no cleanup required"
fi

if [ -d $SRC ]
then
	echo "$SRC exists, copying to tomcat..."
	cp -R $SRC $TOMCAT
else
	echo "$SRC does not exist - not copying"
fi
